version: '3.9'
services:
  postgres:
    image: postgres:14.5-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgressql/data
    extra_hosts: 
      - "host.docker.internal:host-gateway"
volumes:
  db:
    driver: local
