name: CI/CD Pipeline
on: 
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
jobs:
  Build:
    
    runs-on: ubuntu-latest

    strategy:
          matrix:
            node-version: [14.x, 16.x, 18.x]
            
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm run install --if-present
      - run: npm run lint
      - run: npm run test --if-present
      - run: npm run build
      
          